### ISSUE TITLE
ros_core: rclcpp_actions is not included [rolling]

### ISSUE THREAD

**Issue by russkel** [ros2/variants#35]
Using:

```
rosinstall_generator ros_core --rosdistro rolling --deps > rolling-ros-core.rosinstall
```
Does not seem to include `rclcpp_actions` which probably should be part of it?

**Comment by clalancette** [comment]
Excellent point.  We just never noticed before since I think most people use `ros_base` or `desktop`, both of which pull `rclcpp_action` in implicitly.

I personally agree that we should add `rclcpp_action` to the `ros_core`; I definitely consider it "core" now.  @ros2/team, thoughts?

**Comment by russkel** [comment]
It makes sense seeing that the other `rclcpp` packages are also pulled in.

Also is `example_interfaces` considered core as well? That is also missing.

**Comment by clalancette** [comment]
> Also is `example_interfaces` considered core as well? That is also missing.

All of the things that depend on `example_interfaces` are either examples, or the `ros1_bridge`.  Since I don't consider either of those core, I don't think `example_interfaces` should be in `ros_core`.

@russkel Would you mind submitting a PR adding `rclcpp_action` to `ros_core`?

**Comment by russkel** [comment]
> > Also is `example_interfaces` considered core as well? That is also missing.
> 
> All of the things that depend on `example_interfaces` are either examples, or the `ros1_bridge`. Since I don't consider either of those core, I don't think `example_interfaces` should be in `ros_core`.

Yep understood.
 
> @russkel Would you mind submitting a PR adding `rclcpp_action` to `ros_core`?

No problem.
