### ISSUE TITLE
Change desktop_full description to correctly handle quotes.

### ISSUE THREAD

**Issue by hwoithe** [ros2/variants#39]
I am wondering if we could change the `desktop_full` package description to removed or correctly handle quotes for debian packages.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:    22.04
Codename:   jammy

$ apt search ros-.*-desktop-full
Sorting... Done
Full Text Search... Done
ros-humble-desktop-full/jammy 0.10.0-1jammy.20230523.215734 amd64
  Provides a &quot;batteries included&quot; experience to novice users.

ros-iron-desktop-full/jammy 0.10.0-3jammy.20230523.203421 amd64
  Provides a &quot;batteries included&quot; experience to novice users.

ros-rolling-desktop-full/jammy 0.10.0-2jammy.20230523.213549 amd64
  Provides a &quot;batteries included&quot; experience to novice users.
```

**Comment by clalancette** [comment]
Yeah, that's reasonable.  Elsewhere (like in https://github.com/ros2/variants/blob/584545febea0aa5afa0db5c73a936b8a7defbba1/desktop/package.xml#L6), we use single-quotes for this, and that seems to show up fine.

If you'd like to submit a pull request making that change, I'd be happy to review it.

**Comment by MartinPeris** [comment]
I think this issue can be closed
